language: bash
group: edge

git:
  depth: 3

env:
  global:
    - MAKEFLAGS="-j 2"

script: ./build-travis.sh

cache:
  directories:
  - ../buildroot/dl

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
    
#Thanks to @duckinator for this idea.
