language: bash
group: edge

env:
  global:
    - MAKEFLAGS="-j 2"

script: git clone --depth=1 https://github.com/buildroot/buildroot ../buildroot && make skeleton_defconfig && make

notifications:
  email:
    on_success: change # default: change
    on_failure: change # default: always
    
#Thanks to @duckinator for this idea. Now build, damnit!
